INSERT INTO "Skill" (
    "id",
    "ownerId",
    "name",
    "abbreviation",
    "description",
    "category",
    "difficulty",
    "animationName",
    "animationType",
    "steps",
    "animationIds",
    "createdAt",
    "updatedAt",
    "isSystem"
) VALUES
(
    '10000000-0000-4000-8000-000000000029',
    'system',
    '1코 늘리기',
    'M1',
    '코와 코 사이의 실을 들어 새 코를 만들어 늘리는 공통 늘림 기법입니다.',
    '늘림',
    '초급',
    NULL,
    'increase',
    ARRAY['늘릴 위치의 가로 실을 확인해요.', '왼쪽 바늘로 가로 실을 들어요.', '도안 방향에 맞게 떠서 새 코를 만들어요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000030',
    'system',
    '코 줍기',
    'PU',
    '편물 가장자리나 코막음선에서 새 코를 주워 다음 작업을 이어가는 기법입니다.',
    '기본',
    '초급',
    NULL,
    'pickup',
    ARRAY['코를 주울 가장자리를 확인해요.', '간격이 일정하도록 바늘을 넣어요.', '실을 걸어 새 코를 만들어 바늘에 올려요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000031',
    'system',
    '오른코 교차뜨기',
    'RC',
    '오른쪽으로 기울어 보이도록 두 코 또는 여러 코를 교차하는 케이블 기법입니다.',
    '케이블',
    '중급',
    NULL,
    'cable',
    ARRAY['교차할 코 수를 확인해요.', '보조바늘에 지정 코를 뒤쪽 또는 앞쪽으로 옮겨요.', '남은 코와 보조바늘 코를 순서대로 떠요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000032',
    'system',
    '왼코 교차뜨기',
    'LC',
    '왼쪽으로 기울어 보이도록 두 코 또는 여러 코를 교차하는 케이블 기법입니다.',
    '케이블',
    '중급',
    NULL,
    'cable',
    ARRAY['교차할 코 수를 확인해요.', '보조바늘에 지정 코를 앞쪽 또는 뒤쪽으로 옮겨요.', '남은 코와 보조바늘 코를 순서대로 떠요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000033',
    'system',
    '메리야스뜨기',
    'ST ST',
    '한쪽 면은 겉뜨기, 반대쪽 면은 안뜨기처럼 보이는 가장 기본적인 편물 조직입니다.',
    '무늬',
    '기초',
    NULL,
    'texture',
    ARRAY['왕복뜨기는 겉면에서 겉뜨기, 안면에서 안뜨기를 해요.', '원통뜨기는 모든 단을 겉뜨기해요.', '면의 방향이 바뀌지 않았는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000034',
    'system',
    '가터뜨기',
    'G ST',
    '겉뜨기 줄이 반복되어 양면에 오돌토돌한 줄무늬가 생기는 기본 조직입니다.',
    '무늬',
    '기초',
    NULL,
    'texture',
    ARRAY['왕복뜨기는 매 단 겉뜨기해요.', '원통뜨기는 겉뜨기 단과 안뜨기 단을 번갈아 떠요.', '가터 산의 간격이 일정한지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000035',
    'system',
    '멍석뜨기',
    'MOSS ST',
    '겉뜨기와 안뜨기를 어긋나게 배치해 작은 돌기 무늬를 만드는 조직입니다.',
    '무늬',
    '초급',
    NULL,
    'texture',
    ARRAY['이전 단의 코 모양을 확인해요.', '겉뜨기 위에는 안뜨기, 안뜨기 위에는 겉뜨기를 해요.', '반복이 밀리지 않았는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000036',
    'system',
    '1코 고무뜨기',
    '1X1 RIB',
    '겉뜨기 1코와 안뜨기 1코를 반복해 신축성 있는 조직을 만드는 기법입니다.',
    '무늬',
    '초급',
    NULL,
    'texture',
    ARRAY['겉뜨기 1코, 안뜨기 1코 반복을 확인해요.', '다음 단에서는 보이는 코 모양대로 떠요.', '가장자리에서 반복이 어긋나지 않았는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000037',
    'system',
    '2코 고무뜨기',
    '2X2 RIB',
    '겉뜨기 2코와 안뜨기 2코를 반복해 넓은 골의 신축성 있는 조직을 만드는 기법입니다.',
    '무늬',
    '초급',
    NULL,
    'texture',
    ARRAY['겉뜨기 2코, 안뜨기 2코 반복을 확인해요.', '다음 단에서는 보이는 코 모양대로 떠요.', '반복 단위가 끝까지 맞는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
)
ON CONFLICT ("id") DO NOTHING;
