ALTER TABLE "Skill"
ADD COLUMN "isSystem" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE "UserSkillLevel" (
    "id" UUID NOT NULL,
    "ownerId" TEXT NOT NULL,
    "skillId" UUID NOT NULL,
    "level" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "UserSkillLevel_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "UserSkillLevel_ownerId_skillId_key" ON "UserSkillLevel"("ownerId", "skillId");
CREATE INDEX "UserSkillLevel_ownerId_deletedAt_idx" ON "UserSkillLevel"("ownerId", "deletedAt");
CREATE INDEX "UserSkillLevel_skillId_idx" ON "UserSkillLevel"("skillId");
CREATE INDEX "Skill_isSystem_deletedAt_idx" ON "Skill"("isSystem", "deletedAt");

ALTER TABLE "UserSkillLevel"
ADD CONSTRAINT "UserSkillLevel_ownerId_fkey"
FOREIGN KEY ("ownerId") REFERENCES "UserProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "UserSkillLevel"
ADD CONSTRAINT "UserSkillLevel_skillId_fkey"
FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO "UserProfile" ("id", "displayName", "preferredUnits", "createdAt", "updatedAt")
VALUES ('system', 'KnitGether', 'metric', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "Skill" (
    "id",
    "ownerId",
    "name",
    "abbreviation",
    "description",
    "category",
    "difficulty",
    "animationName",
    "animationType",
    "steps",
    "animationIds",
    "createdAt",
    "updatedAt",
    "isSystem"
) VALUES
(
    '10000000-0000-4000-8000-000000000001',
    'system',
    '겉뜨기',
    'K',
    '오른쪽 바늘로 코의 앞쪽을 떠 새 코를 만드는 기본 뜨기입니다.',
    '기본',
    '기초',
    NULL,
    'basic',
    ARRAY['오른쪽 바늘을 코의 앞쪽에 넣어요.', '실을 감아 코를 통과시켜요.', '새 코를 오른쪽 바늘로 옮겨요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000002',
    'system',
    '안뜨기',
    'P',
    '실을 앞쪽에 두고 코를 떠 겉뜨기와 반대 질감을 만드는 기본 뜨기입니다.',
    '기본',
    '기초',
    NULL,
    'basic',
    ARRAY['실을 바늘 앞쪽에 둬요.', '오른쪽 바늘을 코 앞쪽으로 넣어요.', '실을 감아 새 코를 만들어요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000003',
    'system',
    '코 만들기',
    'CO',
    '작품을 시작하기 위해 필요한 코 수를 바늘에 올리는 과정입니다.',
    '시작/마무리',
    '기초',
    NULL,
    'setup',
    ARRAY['도안의 시작 코 수를 확인해요.', '선택한 방법으로 코를 잡아요.', '코 간격이 균일한지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000004',
    'system',
    '코 막음',
    'BO',
    '완성된 편물이 풀리지 않도록 마지막 코를 정리하는 마무리입니다.',
    '시작/마무리',
    '기초',
    NULL,
    'finish',
    ARRAY['앞의 코를 뒤의 코 위로 넘겨요.', '필요한 장력으로 반복해요.', '마지막 코는 실을 빼 정리해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000005',
    'system',
    '바늘비우기',
    'YO',
    '바늘에 실을 감아 구멍무늬 또는 늘림 효과를 만드는 기법입니다.',
    '무늬/늘림',
    '초급',
    NULL,
    'increase',
    ARRAY['실 위치를 확인해요.', '바늘에 실을 한 번 감아요.', '다음 코를 떠 감긴 실을 새 코로 만들어요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000006',
    'system',
    '코 넘기기',
    'SL',
    '코를 뜨지 않고 다른 바늘로 옮기는 기법입니다.',
    '기본',
    '초급',
    NULL,
    'move',
    ARRAY['도안의 방향을 확인해요.', '코를 뜨지 않고 오른쪽 바늘로 옮겨요.', '다음 지시와 실 위치를 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000007',
    'system',
    '마커 끼우기',
    'PM',
    '반복 구간이나 시작점을 표시하기 위해 마커를 넣는 작업입니다.',
    '마커',
    '기초',
    NULL,
    'marker',
    ARRAY['지시된 위치까지 떠요.', '바늘에 마커를 끼워요.', '마커 다음 지시를 이어서 떠요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000008',
    'system',
    '마커 넘기기',
    'SM',
    '마커를 왼쪽 바늘에서 오른쪽 바늘로 옮겨 위치 표시를 유지합니다.',
    '마커',
    '기초',
    NULL,
    'marker',
    ARRAY['마커 앞까지 떠요.', '마커를 오른쪽 바늘로 옮겨요.', '다음 코부터 도안 지시를 계속해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000009',
    'system',
    '마커 제거',
    'RM',
    '더 이상 필요 없는 마커를 편물에서 빼는 작업입니다.',
    '마커',
    '기초',
    NULL,
    'marker',
    ARRAY['마커 위치를 확인해요.', '마커를 바늘에서 빼요.', '다음 지시를 이어서 진행해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000010',
    'system',
    '오른쪽 기울임 줄임',
    'K2TOG',
    '두 코를 함께 겉뜨기해 오른쪽으로 기울어진 줄임을 만듭니다.',
    '줄임',
    '초급',
    NULL,
    'decrease',
    ARRAY['두 코를 한 번에 오른쪽 바늘로 넣어요.', '두 코를 함께 겉뜨기해요.', '한 코가 줄어든 방향을 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000011',
    'system',
    '안뜨기 두 코 모아뜨기',
    'P2TOG',
    '두 코를 함께 안뜨기해 안뜨기면에서 코를 줄이는 기법입니다.',
    '줄임',
    '초급',
    NULL,
    'decrease',
    ARRAY['실을 앞쪽에 둬요.', '두 코를 함께 안뜨기 방향으로 넣어요.', '두 코를 한 번에 안뜨기해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000012',
    'system',
    '왼쪽 기울임 줄임',
    'SSK',
    '두 코를 옮긴 뒤 함께 떠 왼쪽으로 기울어진 줄임을 만듭니다.',
    '줄임',
    '중급',
    NULL,
    'decrease',
    ARRAY['두 코를 차례로 겉뜨기 방향으로 넘겨요.', '넘긴 코를 다시 왼쪽 바늘로 옮겨요.', '두 코를 함께 겉뜨기해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000013',
    'system',
    '안뜨기 왼쪽 기울임 줄임',
    'SSP',
    '안뜨기면에서 왼쪽으로 기울어진 줄임을 만드는 기법입니다.',
    '줄임',
    '중급',
    NULL,
    'decrease',
    ARRAY['두 코를 차례로 옮겨 방향을 바꿔요.', '코를 다시 왼쪽 바늘에 놓아요.', '두 코를 함께 안뜨기해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000014',
    'system',
    '오른쪽 늘림',
    'M1R',
    '코 사이 가로 실을 들어 오른쪽으로 기울어진 늘림을 만듭니다.',
    '늘림',
    '중급',
    NULL,
    'increase',
    ARRAY['코 사이 가로 실을 왼쪽 바늘에 올려요.', '뒤쪽 방향으로 겉뜨기해요.', '늘어난 코의 방향을 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000015',
    'system',
    '왼쪽 늘림',
    'M1L',
    '코 사이 가로 실을 들어 왼쪽으로 기울어진 늘림을 만듭니다.',
    '늘림',
    '중급',
    NULL,
    'increase',
    ARRAY['코 사이 가로 실을 왼쪽 바늘에 올려요.', '앞쪽 방향으로 겉뜨기해요.', '늘어난 코가 자연스럽게 놓였는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000016',
    'system',
    '안뜨기 오른쪽 늘림',
    'M1RP',
    '안뜨기면에서 오른쪽 방향의 한 코 늘림을 만듭니다.',
    '늘림',
    '중급',
    NULL,
    'increase',
    ARRAY['코 사이 가로 실을 올려요.', '도안 방향에 맞게 안뜨기해요.', '구멍이 생기지 않았는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000017',
    'system',
    '안뜨기 왼쪽 늘림',
    'M1LP',
    '안뜨기면에서 왼쪽 방향의 한 코 늘림을 만듭니다.',
    '늘림',
    '중급',
    NULL,
    'increase',
    ARRAY['코 사이 가로 실을 올려요.', '도안 방향에 맞게 안뜨기해요.', '늘림 방향과 장력을 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000018',
    'system',
    '한 코 앞뒤 겉뜨기',
    'KFB',
    '한 코의 앞과 뒤를 모두 겉뜨기해 한 코를 늘립니다.',
    '늘림',
    '초급',
    NULL,
    'increase',
    ARRAY['한 코의 앞쪽을 겉뜨기해요.', '같은 코를 빼지 않고 뒤쪽도 겉뜨기해요.', '완성한 뒤 코를 왼쪽 바늘에서 빼요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000019',
    'system',
    '한 코 앞뒤 안뜨기',
    'PFB',
    '한 코의 앞과 뒤를 모두 안뜨기해 한 코를 늘립니다.',
    '늘림',
    '중급',
    NULL,
    'increase',
    ARRAY['한 코의 앞쪽을 안뜨기해요.', '같은 코를 빼지 않고 뒤쪽도 안뜨기해요.', '완성한 뒤 코를 왼쪽 바늘에서 빼요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000020',
    'system',
    '뒤코 겉뜨기',
    'KTBL',
    '코의 뒤쪽 다리를 겉뜨기해 꼬인 코를 만듭니다.',
    '꼬임',
    '초급',
    NULL,
    'twist',
    ARRAY['오른쪽 바늘을 코의 뒤쪽에 넣어요.', '실을 감아 겉뜨기해요.', '꼬인 방향을 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000021',
    'system',
    '뒤코 안뜨기',
    'PTBL',
    '코의 뒤쪽 다리를 안뜨기해 꼬인 안뜨기 코를 만듭니다.',
    '꼬임',
    '중급',
    NULL,
    'twist',
    ARRAY['실을 앞쪽에 둬요.', '오른쪽 바늘을 코 뒤쪽에 넣어요.', '뒤쪽 다리를 안뜨기해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000022',
    'system',
    '감아 돌리기',
    'W&T',
    '부분뜨기에서 코를 감아 방향을 바꾸는 기법입니다.',
    '부분뜨기',
    '중급',
    NULL,
    'short-row',
    ARRAY['지시된 위치까지 떠요.', '다음 코를 감싸고 작업 방향을 돌려요.', '나중에 감긴 실을 함께 정리해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000023',
    'system',
    '4코 앞 교차',
    'C4F',
    '두 코를 앞쪽 보조바늘에 두고 다음 두 코와 교차해 케이블을 만듭니다.',
    '케이블',
    '중급',
    NULL,
    'cable',
    ARRAY['앞쪽 보조바늘에 지정 코를 옮겨요.', '다음 코를 떠요.', '보조바늘의 코를 떠서 앞 교차를 만들어요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000024',
    'system',
    '4코 뒤 교차',
    'C4B',
    '두 코를 뒤쪽 보조바늘에 두고 다음 두 코와 교차해 케이블을 만듭니다.',
    '케이블',
    '중급',
    NULL,
    'cable',
    ARRAY['뒤쪽 보조바늘에 지정 코를 옮겨요.', '다음 코를 떠요.', '보조바늘의 코를 떠서 뒤 교차를 만들어요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000025',
    'system',
    '6코 앞 교차',
    'C6F',
    '세 코를 앞쪽 보조바늘에 두고 다음 세 코와 교차하는 케이블입니다.',
    '케이블',
    '중급',
    NULL,
    'cable',
    ARRAY['앞쪽 보조바늘에 지정 코를 옮겨요.', '다음 세 코를 떠요.', '보조바늘의 코를 떠서 교차를 완성해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000026',
    'system',
    '6코 뒤 교차',
    'C6B',
    '세 코를 뒤쪽 보조바늘에 두고 다음 세 코와 교차하는 케이블입니다.',
    '케이블',
    '중급',
    NULL,
    'cable',
    ARRAY['뒤쪽 보조바늘에 지정 코를 옮겨요.', '다음 세 코를 떠요.', '보조바늘의 코를 떠서 교차를 완성해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000027',
    'system',
    '고무뜨기',
    'RIB',
    '겉뜨기와 안뜨기를 반복해 신축성 있는 조직을 만드는 패턴입니다.',
    '무늬',
    '초급',
    NULL,
    'texture',
    ARRAY['도안의 반복 단위를 확인해요.', '겉뜨기와 안뜨기를 순서대로 반복해요.', '행마다 코가 맞는지 확인해요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
),
(
    '10000000-0000-4000-8000-000000000028',
    'system',
    '뒤코로 뜨기',
    'TBL',
    '지시된 코를 뒤쪽 다리로 떠 꼬임 효과를 주는 공통 표기입니다.',
    '꼬임',
    '초급',
    NULL,
    'twist',
    ARRAY['도안이 겉뜨기인지 안뜨기인지 확인해요.', '코의 뒤쪽 다리에 바늘을 넣어요.', '지시된 방식으로 코를 떠요.']::TEXT[],
    ARRAY[]::TEXT[],
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    true
)
ON CONFLICT ("id") DO NOTHING;
